import { Manrope } from "next/font/google";
import "./globals.css";
import Navbar from "./components/shared/Navbar";
import Footer from "./components/shared/Footer";

const manRope = Manrope({
  subsets: ["latin"],
});

export const metadata = {
  title: "OP Ai",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${manRope.className} antialiased`}>{children}</body>
    </html>
  );
}
